env: local
http_server:
  host: "localhost"
  port: "8080"
  sso_port: "8082"
  timeout: 4s
  idle_timeout: 60s
postgres_config:
  host: "db"
  port: "5432"
  database: "BajoJajo"
aws_config:
  aws_default_region: "ru-msk"
  bucket_name: "bajojajo"
  hotbox_endpoint: "https://hb.ru-msk.vkcloud-storage.ru"
grpc_server:
  port: 44044
  timeout: 5s
token_ttl: 1h