apiPath: "/api/v1/"
# server:
#   user: "postgres"
#   database: "tpTinder"
#   password: "postgres"
#   host: "localhost"
#   port: 5432
#   timer: 1
server:
  host: "localhost"
  port: ":8087"
  swaggerPort: ":8085"
  timeout: 30

database:
  host: "localhost"
  port: "5432"
  dbname: "BajoJajo"
  user: "postgres"
  password: "admin"
  timer: 30
  max_open_conns: 10